name: WoolBattle
main: Fludixx\WoolBattle\Main
version: 1.2.2
api: [4.0.0]
author: Fludixx
description: WoolBatlle Plugin for pmmp
website: https://github.com/Fludixx/
commands:
    eq:
        description: "Gives you Woolbattle Equip"
    perkshop:
        description: "WoolBattle PerkShop"
    cords:
        description: "Cords -> Woolbattle"
    spectate:
        description: "Spectate -> Woolbattle"
        aliases: ["spec", "zuschauen"]
    lobby:
        description: "Teleport to Woolbattle Lobby"
        aliases: ["l", "leave"]
    group:
        description: "Woolbattle Group (ClanWar) System"
        aliases: ["gp", "g", "gruppe"]
    lastaction:
        description: "Output the last registered Action!"
        aliases: ["la", "letzteaction"]
